angular.module('amcomanApp')
    .factory('SimpleMockData', function () {
        var smdfac = {};
        smdfac.nutrientsList = {
            "pages": 5,
            "page": 1,
            "totalRecords": 100,
            "pageSize": 20,
            "thisPageSize": 100,
            "categoryId": 0,
            "categoryName": "Acne",
            "aflProducts": [
                {
                    "prodId": 31740,
                    "productName": " Baby Quasar + Baby Blue Power Pack, 1 set ",
                    "description": "<span style=\"font-style: Normal;font-weight: bold;\">Bringing the Spa Home  Package Contains: <ul start=\"1\" style=\"list-style-type:disc\"><li value=\"1\"><span style=\"font-style: Normal;font-weight: bold;\">Baby Quasar  <span style=\"font-style: Italic;font-weight: normal;\">Reduces the appearance of fine lines and wrinkles   Travel Pouch   User Manual   International Power Supply   Pure Silk Serum Sample <span style=\"\" /> <li value=\"2\"><span style=\"font-style: Normal;font-weight: bold;\">Baby Blue  <span style=\"font-style: Italic;font-weight: normal;\">Kills the bacteria that causes acne   Travel Pouch   User Manual   International Power Supply  <span style=\"font-style: Normal;font-weight: bold;\">Show Your Skin the Light   Gorg",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.213389&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/213389/300.JPG",
                    "imgAlt": " Baby Quasar + Baby Blue Power Pack, 1 set ",
                    "imgDescription": " Baby Quasar + Baby Blue Power Pack, 1 set ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 749,
                    "advertizerLinkID": "213389",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31741,
                    "productName": " Clean & Clear Advantage Acne Spot Treatment, .75 fl oz ",
                    "description": "Salicylic Acid Acne Medication     Quickly reduces pimple size and redness    Won t overdry skin   Clean & Clear® Advantage Acne Spot Treatment has a unique formula that quickly reduces the visible signs of breakouts.  That s because Clean & Clear® Advantage Acne Spot Treatment is a breakthrough in acne fighting.  In clinical testing, this clear formula was shown to make pimples smaller and visibly reduce pimple redness.  In just days, you will see noticeably clearer skin.  Plus, this unique formula will treat pimples without overdrying - leaving your skin looking clear and beautiful.  Give yourself an unfair advantage with new Clean & Clear® Advantage Acne Spot Treatment.  Questions?  ;",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.87659&type=15&subid=0",
                    "imgUrl": "http://pics1.ds-static.com/prodimg/87659/300.jpg",
                    "imgAlt": " Clean & Clear Advantage Acne Spot Treatment, .75 fl oz ",
                    "imgDescription": " Clean & Clear Advantage Acne Spot Treatment, .75 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 7.49,
                    "advertizerLinkID": "87659",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": true
                },
                {
                    "prodId": 31742,
                    "productName": " University Medical AcneFree Oil-Free 3-in-1 Acne Night Repair Leave-On Foam, 3 oz ",
                    "description": "Kills 99% of acne bacteria on contact.     12-hour continuous-release formula works throughout the night.  Non-sticky, fast-absorbing, and controls shine.    ;",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.365218&type=15&subid=0",
                    "imgUrl": "http://pics1.ds-static.com/prodimg/365218/300.JPG",
                    "imgAlt": " University Medical AcneFree Oil-Free 3-in-1 Acne Night Repair Leave-On Foam, 3 oz ",
                    "imgDescription": " University Medical AcneFree Oil-Free 3-in-1 Acne Night Repair Leave-On Foam, 3 oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 7.99,
                    "advertizerLinkID": "365218",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31743,
                    "productName": " LORAC Wet/Dry Powder Makeup Foundation, WD2.5, .35 oz ",
                    "description": "LORAC s best selling Oil-Free Wet/Dry Powder Makeup instantly gives you picture perfect coverage.  This non-drying powder with Sodium Hyaluronate is 100% Oil and Fragrance Free and is infused with Vitamins A and E to nourish and condition, while Nylon 12 gives you an even silky-smooth finish.  Good for all skin types - especially sensitive, oily and acne-prone skin.   Foundation, WD2.5",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.150634&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/150634?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " LORAC Wet/Dry Powder Makeup Foundation, WD2.5, .35 oz ",
                    "imgDescription": " LORAC Wet/Dry Powder Makeup Foundation, WD2.5, .35 oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 36,
                    "advertizerLinkID": "150634",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31744,
                    "productName": " ARCONA Tabula Rasa, 1.17 oz ",
                    "description": "Normal and Problematic Skin Types   Spot specific acne fighting formula heals blemishes and reduces enlarged pores, soothes ingrown hairs and razor burn.  Exfoliate , unclog pores, combat skin eruptions and kill bacteria with lactic acid.  Stimulate cell renewal with allantoin and grape seed extract.  Cleanse and increase circulation with naturally antiseptic witch hazel.  Like all products in ARCONA s skin therapy regimen, Tabula Rasa is cosmeceutically formulated with pure, natural ingredients, cold-pressed in small batches to keep them fresh, active and super-effective.  For optimal results, we recommend using this product within six months of opening.  Change may be immediately noticeable;  however, full benefits are derived as skin is brought into balance by regular use.",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.162971&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/162971?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " ARCONA Tabula Rasa, 1.17 oz ",
                    "imgDescription": " ARCONA Tabula Rasa, 1.17 oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 22,
                    "advertizerLinkID": "162971",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31745,
                    "productName": " CLARISONIC Replacement Brush Head, Delicate Skin, 2 ea ",
                    "description": "Now you can purchase Brush Heads in convenient packs of two.  These Twin-Packs are valued at $50, so you ll save $10 for every set you purchase.  An ultra-soft brush for those with delicate or extra-sensitive skin and for skin sensitivities like rosacea and acne-prone skin.   All CLARISONIC® brush heads are made from a nonporous, soft elastomeric material, resistant to bacterial attachment.  All brush heads are precision-designed to oscillate bi-directionally at a sonic frequency.   For use with the CLARISONIC skin care brush.",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.228320&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/228320?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " CLARISONIC Replacement Brush Head, Delicate Skin, 2 ea ",
                    "imgDescription": " CLARISONIC Replacement Brush Head, Delicate Skin, 2 ea ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 40,
                    "advertizerLinkID": "228320",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31746,
                    "productName": " Clearasil Ultra Acne + Marks Wash and Mask, 6.78 fl oz ",
                    "description": "<span style=\"font-style: Normal;font-weight: bold;\">Dermatologist-tested Clearasil Ultra Acne+Marks Wash and Mask removes dirt and oil from pores, resulting in visibly clearer skin fast.  <span style=\"font-style: Normal;font-weight: bold;\">Package Contents  Clearasil Ultra Acne+Marks Wash and Mask  with salicylic acid 2% acne medication.  The Acne+Marks Wash and Mask is scientifically formulated with maximum strength acne medication and can be used as either a face wash or a deep treatment mask.  <span style=\"font-style: Normal;font-weight: bold;\">Product Features <span style=\"\" /> <ul start=\"1\" style=\"list-style-type:disc\"><li value=\"1\"> Helps clear pimples fast and reduce the appearance of acne <li value=\"2\"> Designed to work on your skin from the start of a pimple",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.336004&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/336004/300.JPG",
                    "imgAlt": " Clearasil Ultra Acne + Marks Wash and Mask, 6.78 fl oz ",
                    "imgDescription": " Clearasil Ultra Acne + Marks Wash and Mask, 6.78 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 9.49,
                    "advertizerLinkID": "336004",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31747,
                    "productName": " Clearasil Ultra Rapid Action Pads, 90 ea ",
                    "description": "<span style=\"font-style: Normal;font-weight: bold;\">Clearasil Ultra Rapid Action Pads quickly and effectively visibly reduce redness and pimple size in as little as four hours.  <span style=\"font-style: Normal;font-weight: bold;\">Package Contents  Clearasil Ultra Rapid Action Pads  with salicylic acid 2% acne medication. <span style=\"font-style: Normal;font-weight: bold;\" />  Formulated with maximum-strength acne medication, the dermatologist-tested pads remove dirt, oil, and bacteria from deep within your pores. They are packed in a convenient jar for use practically anywhere--in the car, at the gym, or at work.  <span style=\"font-style: Normal;font-weight: bold;\">Product Features <ul start=\"1\" style=\"list-style-type:disc\"><li value=\"1\"> Visibly reduces pimple size and redness in a",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.139461&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/139461/300.jpg",
                    "imgAlt": " Clearasil Ultra Rapid Action Pads, 90 ea ",
                    "imgDescription": " Clearasil Ultra Rapid Action Pads, 90 ea ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 8.99,
                    "advertizerLinkID": "139461",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31748,
                    "productName": " Clinicians Complex Microdermabrasion Cream, 2 oz ",
                    "description": "Microdermabrasion Cream is designed to improve the appearance and texture of the skin.     This formula utilizes diamond shaped crystals to exfoliate and rejuvenate.  It helps smooth fine lines, wrinkles, lighten skin discoloration and pigmentation.  It is also great for acne prone skin.  Ideal for the face, neck hands and body.  The results are amazing and can be seen and felt immediately.",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.78929&type=15&subid=0",
                    "imgUrl": "http://pics1.ds-static.com/prodimg/78929/300.jpg",
                    "imgAlt": " Clinicians Complex Microdermabrasion Cream, 2 oz ",
                    "imgDescription": " Clinicians Complex Microdermabrasion Cream, 2 oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 59,
                    "advertizerLinkID": "78929",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31749,
                    "productName": " Desert Essence Organic Tea Tree Oil, .5 fl oz ",
                    "description": "Desert Essence Organic Tea Tree Oil is an inherently antiseptic essential oil organically grown in Australia, free of herbicides, pesticides or chemicals.  Organically grown in accordance with the California Organic Foods Act of 1990.   Desert Essence   Vegan",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.83681&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/83681/300.jpg",
                    "imgAlt": " Desert Essence Organic Tea Tree Oil, .5 fl oz ",
                    "imgDescription": " Desert Essence Organic Tea Tree Oil, .5 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 8.99,
                    "advertizerLinkID": "83681",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31750,
                    "productName": " Viatek DermaBrite Deluxe 4-in-1 Facial Light Therapy, 1 ea ",
                    "description": "Derma Bright Deluxe light therapy treatment uses a proven light therapy to target skin troubles including acne, wrinkles, fine lines, age spots, and hyper pigmentation. The revolutionary LED light therapy uses specific LED light wave lengths that are absorbed by the skin during 15 minutes of safe, painless treatment. Includes 1.5oz After Treatment Cream  DermaBrite products are UV Free, safe, and non-toxic for guaranteed results with no post treatment down time. Just 15 minutes a day can help clear your skin of conditions such as: Fine lines and wrinkles, redness, and pigmentation problems, age spots, and acne prone skin.",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.269747&type=15&subid=0",
                    "imgUrl": "http://pics1.ds-static.com/prodimg/269747/300.JPG",
                    "imgAlt": " Viatek DermaBrite Deluxe 4-in-1 Facial Light Therapy, 1 ea ",
                    "imgDescription": " Viatek DermaBrite Deluxe 4-in-1 Facial Light Therapy, 1 ea ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 99.99,
                    "advertizerLinkID": "269747",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31751,
                    "productName": " Alba Botanica Natural AcneDote Deep Clean Astringent, 6 oz ",
                    "description": "Reduces Breakouts In 8 Hours    Oil Free  Maximum Strength  Dermatologist Tested  Non Comedogenic  100% Vegetarian Ingredients.  No : Animal Testing, Artificial Fragrances, Artificial Colors, Sulfates, Parabens, Phthalates or Petrochemicals   Got an oily spill?   Eradicate icky oil with this powerfully natural, botanically effective cooling astringent that penetrates deep to help prevent zits before they start. formulated with proven zit zapper ,Salicylic Acid , this oil dissolver unclogs pores for a visibly clearer complexion without over irritation. Instantly, skin is super clean, without a trace of oil. In just 8 hours, breakouts are reduced. Over time, scars and acne marks fade.  70% tested saw clearer skin in just 7 days.*  *Based on consumer evaluation  For Details Call    Made In USA",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.358287&type=15&subid=0",
                    "imgUrl": "http://pics1.ds-static.com/prodimg/358287/300.JPG",
                    "imgAlt": " Alba Botanica Natural AcneDote Deep Clean Astringent, 6 oz ",
                    "imgDescription": " Alba Botanica Natural AcneDote Deep Clean Astringent, 6 oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 9.95,
                    "advertizerLinkID": "358287",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31752,
                    "productName": " Neutrogena Naturals Purifying Facial Cleanser, 6 fl oz ",
                    "description": "New   Gently Removes Impurities & Improves Complexion for Fresh, Clean Skin    Willowbark bionutrient rich cleanser detoxifies pores   No harsh chemical sulfates, parabens, petrochemicals, dyes, phthalates   Neutrogena® Naturals Purifying Facial Cleanser gently washes away impurities and detoxifies pores for fresh,  clear skin.  This face wash contains natural salicylic acid from Willowbark bionutrients that penetrate deep into skin to remove dirt, oil and make up.  Rinses clean with no pore clogging residue.  Suitable for acne prone skin.  We ve carefully formulated this product to be 90% naturally derived.   This product was not tested on animals.   ;  Ingredient Note: *The remaining ingredient are essential to blend the product together and maintain effectiveness.",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.328544&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/328544/300.JPG",
                    "imgAlt": " Neutrogena Naturals Purifying Facial Cleanser, 6 fl oz ",
                    "imgDescription": " Neutrogena Naturals Purifying Facial Cleanser, 6 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 7.99,
                    "advertizerLinkID": "328544",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31753,
                    "productName": " no!no! Skin Acne Treatment System, 1 ea ",
                    "description": "No Acne  - No Pain - No Chemicals - No Cuts No Stress - No Mess - No Time   The Healing Power of Light & Heat Small, light-weight and easy to use, no!no! Skin with LHE® technology painlessly stops pimples in their tracks.  Trusted by doctors and skin care professionals around the world, LHE technology safely and effectively treats all skin colors with no burning or scarring.  Enjoy the same care as a combination of Light and Heat pulses target and eliminate pimples at their source.  There are no chemicals and no medications.  Simply place no!no! Skin over a pimple, push the button and in 10 seconds, you are on your way to clearer, cleaner and healthier looking skin.  no!no! Skin is clinically proven to be effective.",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.226893&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/226893/300.JPG",
                    "imgAlt": " no!no! Skin Acne Treatment System, 1 ea ",
                    "imgDescription": " no!no! Skin Acne Treatment System, 1 ea ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 180,
                    "advertizerLinkID": "226893",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31754,
                    "productName": " clickR No More Drama Total Acne Face Care Mini Kit, 1 kit ",
                    "description": "The quick-fix kit for blemish-prone younger skin, see results in 24 hours*, gets along with makeup , no benzoyl peroxide   Kit Includes:    Acne Spot Serum  Daily Dermabrasion Wash   clickR skin care formulations are new and unique, made of nourishing but purposeful ingredients that your young skin craves.   Each and every element is here for a reason, to make clickR skin care fast-acting, incredibly effective and gentle on your skin. And every ingredient comes from plant or mineral origins, so it s not only seriously effective, it s totally natural.    clickR uses no artificial colors. No parabens. No phthalates. No sulfates or petrochemicals. No endocrine disruptors, benzoyl peroxide or allergen fragrances.   Clinically tested, safe and effective for everyday use and all skin types, even sensitive skin. And no animal testing whatsoever.     Naturally pure. Always vegan",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.329421&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/329421?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " clickR No More Drama Total Acne Face Care Mini Kit, 1 kit ",
                    "imgDescription": " clickR No More Drama Total Acne Face Care Mini Kit, 1 kit ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 21,
                    "advertizerLinkID": "329421",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31755,
                    "productName": " Philips Light Therapy Wake-up Light, iPhone Operated, HF3550/60, 1 ea ",
                    "description": "<span style=\"font-style: Normal;font-weight: bold;\">Wake Up Naturally   With a Wake-Up Light® Controlled by Your iPhone®  Inspired by nature’s sunrise a unique combination of light and sound wakes you in a more natural way.  Use the App to set your alarms and play music.  The dock also charges your iPhone.  <span style=\"font-style: Normal;font-weight: bold;\">Controlled by iPhone App <ul start=\"2\" style=\"list-style-type:disc\"><li value=\"2\"> Control your Wake-up Light by using the free Wake-up App <li value=\"1\"> Wake up with songs from your iPhone or 8 natural sounds <li value=\"4\"> Charge your iPhone in Docking station <li value=\"3\"> Track your sleep routines with the Wake-up App  <span style=\"font-style: Normal;font-weight: bold;\"&",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.458120&type=15&subid=0",
                    "imgUrl": "http://pics2.ds-static.com/prodimg/458120/300.JPG",
                    "imgAlt": " Philips Light Therapy Wake-up Light, iPhone Operated, HF3550/60, 1 ea ",
                    "imgDescription": " Philips Light Therapy Wake-up Light, iPhone Operated, HF3550/60, 1 ea ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 199.99,
                    "advertizerLinkID": "458120",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31756,
                    "productName": " Peter Thomas Roth Anti Aging Cleansing Gel for All Skin Types Except Sensitive, 8 fl oz ",
                    "description": "Get ultra-clean, refined and radiant skin with this exhilarating facial cleanser. Advanced deep pore resurfacing action helps diminish signs of aging, detoxifies pores, dissolves makeup, emulsifies oil and improves skin texture.  Anti-wrinkle technology rejuvenates, clarifies, and brightens with glycolic acid, salicylic acid, extracts of peach, white oak bark, lemon, lime, linden, citric grapefruit, and arginine.  For all skin types except ultra sensitive.  Luxurious, anti-aging facial cleansing gel provides an exhilerating, peachy clean freshness to help produce a beautiful, fresh, youthful-looking complexion.  An advanced deep pore resurfacing actiion increases cell turnover to help diminish the appearance of fine lines, wrinkles and other signs of aging.  Ideal for all skin types, including dry, sun damaged, normal, combination, oily and acne prone skin, except sensitive ski",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.76377&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/76377?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " Peter Thomas Roth Anti Aging Cleansing Gel for All Skin Types Except Sensitive, 8 fl oz ",
                    "imgDescription": " Peter Thomas Roth Anti Aging Cleansing Gel for All Skin Types Except Sensitive, 8 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 35,
                    "advertizerLinkID": "76377",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31757,
                    "productName": " Murad Acne Clarifying Body Spray, 4.3 fl oz ",
                    "description": "Skin Type:   Problem Skin  0.5% Salicylic Acid Acne Treatment   Step 2:   Treat   Repair  Clear your body.  Purifying salicylic acid works with powerful antibacterial agents to penetrate pores and reduce acne blemished while helping prevent new breakouts from forming.  Skin conditioners soothe and hydrate irritated skin for maximum clarity.  360° spray works upside down for hard to reach places.     Triclosan, a powerful antibacterial agent, helps to fight acne breakouts    Retinol and Salicylic Acid penetrate pores to keep them clear    Allantoin, a powerful healing agent, helps keep skin healthy    As a leader in research and development, Murad has long been at the forefront of skincare science.  Using insights from my dermatology practice and the Murad Spa, we continue this tradition.   Ours is an inclusive health philosophy, a comprehensive inside",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.79758&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/79758?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " Murad Acne Clarifying Body Spray, 4.3 fl oz ",
                    "imgDescription": " Murad Acne Clarifying Body Spray, 4.3 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 37,
                    "advertizerLinkID": "79758",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31758,
                    "productName": " Logona Blemish Stick, Organic Mint, .2 fl oz ",
                    "description": "<span style=\"font-style: Normal;font-weight: bold;\">Quick response blemish treatment   Fights pimples and other blemishes intensively, but gently, with a bio-active blend of usnea barbata, sage, mint, green tea and witch hazel.  <span style=\"font-style: Normal;font-weight: bold;\"> ;",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=221686.401282&type=15&subid=0",
                    "imgUrl": "http://pics1.ds-static.com/prodimg/401282/300.JPG",
                    "imgAlt": " Logona Blemish Stick, Organic Mint, .2 fl oz ",
                    "imgDescription": " Logona Blemish Stick, Organic Mint, .2 fl oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "drugstore.com",
                    "price": 14,
                    "advertizerLinkID": "401282",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                },
                {
                    "prodId": 31759,
                    "productName": " DIANA B. Sugar Scrub (Originally $55! Beauty.com Special), Maple Sugar Lychee Nut, 21 oz ",
                    "description": "Notes:Top Note: Lychee and sugarMiddle Note: Maple and burnt vanillaBottom Note: Bourbon vanilla  Maple Sugar Lychee Nut The fresh scent of lychee nut fruit and white flowers combined with notes of warm maple.  The first scrub ever created by DIANA B., this formula inspired by her trip to Morocco, is a miracle cure for all types of skin imperfections including sun damage, acne scaring and topical infections.  DIANA B. Maple Sugar Lychee Nut Sugar Scrub is filled with maple syrup, rarely found in beauty products, has a high volume of minerals and remarkable healing properties.   Sugar Scrub , Maple Sugar Lychee Nut",
                    "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=250677.218151&type=15&subid=0",
                    "imgUrl": "http://s7d2.scene7.com/is/image/Drugstore/218151?wid=300&hei=300&op_sharpen=1",
                    "imgAlt": " DIANA B. Sugar Scrub (Originally $55! Beauty.com Special), Maple Sugar Lychee Nut, 21 oz ",
                    "imgDescription": " DIANA B. Sugar Scrub (Originally $55! Beauty.com Special), Maple Sugar Lychee Nut, 21 oz ",
                    "additionalInfoTitle": null,
                    "additionalInfoUrl": null,
                    "recordStatus": null,
                    "linkCode": null,
                    "advertiser": "Beauty.com",
                    "price": 45,
                    "advertizerLinkID": "218151",
                    "categoryId": 0,
                    "categoryName": null,
                    "detailIsActive": false
                }
            ]
        };

        smdfac.nutrientItem = {
            "desc1": "Green Barley 1",
            "desc2": "Green Barley 2 Green Barley 2 Green Barley 2 Green Barley 2 Green Barley 2 ",
            "title": "Green Barley Title",
            "metaKeywords": "Meta Keywords for green barley",
            "metaDescription": "Meta Description for Green barley",
            "articleTitle": "Green barley article Title",
            "prodId": 1682,
            "productName": "GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets",
            "description": "GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets  ",
            "navigateUrl": "http://click.linksynergy.com/fs-bin/click?id=pSK2wtK8sX8&offerid=116038.5840&type=2&subid=0",
            "imgUrl": "http://www.puritan.com/VF/Assets/Puritan_Products/005840.jpg",
            "imgAlt": "GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets",
            "imgDescription": "GREEN BARLEY GRASS 500 mg-500 mg-120-Tablets",
            "additionalInfoTitle": null,
            "additionalInfoUrl": null,
            "recordStatus": null,
            "linkCode": null,
            "advertiser": "Puritan's Pride",
            "price": 8.99,
            "advertizerLinkID": "5840",
            "categoryId": 0,
            "categoryName": null,
            "detailIsActive": true
        };
        smdfac.loginResponse = {
            access_token : "dummy token",
            expires_in : 3600,
            token_type : "bearer",
            username : "Dummy admin name",
            user_role: 'admin'
        }
        return smdfac;
        });